### ISSUE TITLE
Glift for Drupal

### ISSUE THREAD

**Issue by varenius** [gogameguru/glift-go-game#1]
Hello,
As you know I am developing Glift for Drupal at https://www.drupal.org/sandbox/varenius/2345991. I started off by solving a few basic things myself to get a feeling for Drupal module writing and Glift. Now when I have a basic version working, I decided to look at the wordpress code for inspiration. I find it very well structured and clear to read - well done! I notice you solved a few things in a better way than I did, and other things that I thought about you have also adressed. I fact, I decided to incorporate most of it into the Drupal version. Since the Wordpress development seems closely tied with the Glift development, I think that it is good if the Drupal development can be synchronised as closely as possible to this wordpress plugin development. Hence, in the coming days I will try to modify the Drupal module code to be an interface to the classes and tools already written within the wordpress plugin. That way, I hope that once glift is updated, it will be reflected in the wordpress plugin, and some updates could then be very easily (perhaps straight copy-paste or file-replacement) transferred from the Wordpress plugin to the Drupal module.

Again, great work - I will keep you posted on the news from the Drupal side.
Best,
Eskil

**Comment by dormerod** [comment]
Thanks Eskil,

Sorry for not replying to this comment earlier. I was very busy helping customers etc in the months before Christmas last year and never managed to get back to you.

I agree that it would be better if the code could be reused as much as possible and I'm happy if you can use some of my work to save time. You may have noticed that the WordPress plugin makes fairly heavy use of native WordPress functions and APIs. Because of that, I wonder whether it would be better to make the code more modular and move all the platform dependent stuff to one place. For example, maybe we could write some wrappers for the functions that are native to WordPress/Drupal/Joomla etc and keep the rest generic? Please let me know whether you think that would be feasible in this case.

I've tried my best to make the code as clear and readable as possible, but I think it could still be improved a lot in terms of architecture and modularity. This is still a very early version.

Also, you'll notice in the latest version in the develop branch that there's a lot of new code to add a settings page in WordPress. This is an example of something that would have to be totally rewritten for Drupal and I was worried about that when I originally saw your comment last year. Still, I think these issues could be solved with a smarter design :)

**Comment by varenius** [comment]
Hi again,
Good points and ideas. Unfortunately my time is very limited at the moment so I do not have time to dive in to this or come with suggestions right now. If I find the time later this spring I might contact you again to discuss the best way to share code between the modules. 
Best,
Eskil

**Comment by dormerod** [comment]
No worries. Thanks Eskil and sorry that the timing didn't work out well between us. Feel free to get in touch any time and hopefully I'll see you over at GGG in any case :)

David
